### ISSUE TITLE
Homepage To-do list (10/05/24)

### ISSUE THREAD

**Issue by muskwebezy** [Reap-Agency/lexxola#60]
To-do list (10/05/24)
## DESKTOP 

- [ ] 1.  Remove button, adapt functionality as per the Figma design [There will be text **Shop Kiss Kiss** with an underline] 
- [ ] 2.  The width from the left side & the bottom height of the text **_Shop Kiss Kiss_** will be 42px
- [ ] 3.  Distance between the banner and the product image should be 42px
- [ ] 4.  Gap between two products image should be 42px
- [ ] 5.  Space above product image should be 42px
- [ ] 6.  Gap between the product image and text will be 21px (from top and bottom) 
- [ ] 7.  Product text font & size will be Montserrat Regular 12
- [ ] 8.  In header, remove the line underneath **_Lexxola._** Adapt new floated appearance as shown in Figma
- [ ] 9.  Remove the moving banner**

## MOBILE

- [ ] 1.  Height of the banner should be 576px
- [ ] 2.  The width from the left side & bottom height of the text **_Shop Kiss Kiss_** will be 20px
- [ ] 3.  In header, remove the line underneath **_Lexxola_**. Adapt new floated appearance as shown in Figma.
- [ ] 4.  Remove the moving banner.

## Additional Info:
[Figma Link](https://www.figma.com/design/vlvH3BTZmlPKrMZCbZikNI/Lexxola?node-id=5767%3A1720&t=j2vnc6uMTCCsNe9J-1)
